# Generated by Django 6.0 on 2026-01-10 06:02

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin_user(apps, schema_editor):
    # We get the model from the historical version 'apps'
    User = apps.get_model('api', 'User')

    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            password=make_password('admin123'),  # Hash the password
            first_name='System',
            last_name='Admin',
            role='admin',        # Critical for your frontend logic
            is_staff=True,       # Required for Django Admin panel
            is_superuser=True,   # Required for full permissions
            is_active=True
        )
        print("\n✅ Default Admin Account Created: username='admin', password='admin123'")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_section_teacher'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]



