# Generated by Django 6.0 on 2026-02-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
